/**
 * madana-api
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The JsonAnalysisRequestAction model module.
 * @module model/JsonAnalysisRequestAction
 * @version 0.4.12
 */
class JsonAnalysisRequestAction {
    /**
     * Constructs a new <code>JsonAnalysisRequestAction</code>.
     * 
     * @alias module:model/JsonAnalysisRequestAction
     */
    constructor() { 
        
        JsonAnalysisRequestAction.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JsonAnalysisRequestAction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JsonAnalysisRequestAction} obj Optional instance to populate.
     * @return {module:model/JsonAnalysisRequestAction} The populated <code>JsonAnalysisRequestAction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonAnalysisRequestAction();

            if (data.hasOwnProperty('requestID')) {
                obj['requestID'] = ApiClient.convertToType(data['requestID'], 'String');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = ApiClient.convertToType(data['user'], 'String');
            }
            if (data.hasOwnProperty('connection')) {
                obj['connection'] = ApiClient.convertToType(data['connection'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'String');
            }
            if (data.hasOwnProperty('fingerprint')) {
                obj['fingerprint'] = ApiClient.convertToType(data['fingerprint'], 'String');
            }
            if (data.hasOwnProperty('application')) {
                obj['application'] = ApiClient.convertToType(data['application'], 'String');
            }
            if (data.hasOwnProperty('action')) {
                obj['action'] = ApiClient.convertToType(data['action'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }


}

/**
 * 
 * @member {String} requestID
 */
JsonAnalysisRequestAction.prototype['requestID'] = undefined;

/**
 * 
 * @member {String} user
 */
JsonAnalysisRequestAction.prototype['user'] = undefined;

/**
 * 
 * @member {String} connection
 */
JsonAnalysisRequestAction.prototype['connection'] = undefined;

/**
 * 
 * @member {String} date
 */
JsonAnalysisRequestAction.prototype['date'] = undefined;

/**
 * 
 * @member {String} fingerprint
 */
JsonAnalysisRequestAction.prototype['fingerprint'] = undefined;

/**
 * 
 * @member {String} application
 */
JsonAnalysisRequestAction.prototype['application'] = undefined;

/**
 * 
 * @member {String} action
 */
JsonAnalysisRequestAction.prototype['action'] = undefined;

/**
 * 
 * @member {String} details
 */
JsonAnalysisRequestAction.prototype['details'] = undefined;

/**
 * 
 * @member {String} signature
 */
JsonAnalysisRequestAction.prototype['signature'] = undefined;






export default JsonAnalysisRequestAction;

