/**
 * madana-api
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JsonMDNSocialUserObject from './JsonMDNSocialUserObject';
import JsonMDNUserCredentials from './JsonMDNUserCredentials';
import JsonMDNUserSetting from './JsonMDNUserSetting';

/**
 * The JsonMDNUserAllOf model module.
 * @module model/JsonMDNUserAllOf
 * @version 0.4.12
 */
class JsonMDNUserAllOf {
    /**
     * Constructs a new <code>JsonMDNUserAllOf</code>.
     * @alias module:model/JsonMDNUserAllOf
     */
    constructor() { 
        
        JsonMDNUserAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JsonMDNUserAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JsonMDNUserAllOf} obj Optional instance to populate.
     * @return {module:model/JsonMDNUserAllOf} The populated <code>JsonMDNUserAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JsonMDNUserAllOf();

            if (data.hasOwnProperty('mail')) {
                obj['mail'] = ApiClient.convertToType(data['mail'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('guid')) {
                obj['guid'] = ApiClient.convertToType(data['guid'], 'String');
            }
            if (data.hasOwnProperty('settings')) {
                obj['settings'] = ApiClient.convertToType(data['settings'], [JsonMDNUserSetting]);
            }
            if (data.hasOwnProperty('socialAccounts')) {
                obj['socialAccounts'] = ApiClient.convertToType(data['socialAccounts'], [JsonMDNSocialUserObject]);
            }
            if (data.hasOwnProperty('credentials')) {
                obj['credentials'] = JsonMDNUserCredentials.constructFromObject(data['credentials']);
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
        }
        return obj;
    }


}

/**
 * 
 * @member {String} mail
 */
JsonMDNUserAllOf.prototype['mail'] = undefined;

/**
 * 
 * @member {String} lastName
 */
JsonMDNUserAllOf.prototype['lastName'] = undefined;

/**
 * 
 * @member {String} guid
 */
JsonMDNUserAllOf.prototype['guid'] = undefined;

/**
 * 
 * @member {Array.<module:model/JsonMDNUserSetting>} settings
 */
JsonMDNUserAllOf.prototype['settings'] = undefined;

/**
 * 
 * @member {Array.<module:model/JsonMDNSocialUserObject>} socialAccounts
 */
JsonMDNUserAllOf.prototype['socialAccounts'] = undefined;

/**
 * @member {module:model/JsonMDNUserCredentials} credentials
 */
JsonMDNUserAllOf.prototype['credentials'] = undefined;

/**
 * 
 * @member {String} firstName
 */
JsonMDNUserAllOf.prototype['firstName'] = undefined;






export default JsonMDNUserAllOf;

