/**
 * madana-api
 * <h1>API Quickstart Guide</h1>        <p>This documentation contains a Quickstart Guide, a few <a href=\"downloads.html\">sample clients</a>  for download and information about the available  <a href=\"resources.html\">endpoints</a>  and  <a href=\"data.html\">DataTypes</a>  </p>     <p>The <a target=\"_blank\" href=\"http://madana-explorer-staging.eu-central-1.elasticbeanstalk.com/login\">  MADANA Explorer</a> can be used to verify the interactions with the API</p>           <p>Internal use only. For more information visit <a href=\"https://www.madana.io\">www.madana.io</a></p>         <br> <br>
 *
 * The version of the OpenAPI document: 0.4.12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import JsonAnalysis from './model/JsonAnalysis';
import JsonAnalysisAllOf from './model/JsonAnalysisAllOf';
import JsonAnalysisRequest from './model/JsonAnalysisRequest';
import JsonAnalysisRequestAction from './model/JsonAnalysisRequestAction';
import JsonAnalysisResult from './model/JsonAnalysisResult';
import JsonAnalysisResultSubGroup from './model/JsonAnalysisResultSubGroup';
import JsonAnalysisResultSubGroupAllOf from './model/JsonAnalysisResultSubGroupAllOf';
import JsonAnalysisVisualization from './model/JsonAnalysisVisualization';
import JsonDatasetInfo from './model/JsonDatasetInfo';
import JsonDatasetInfoAllOf from './model/JsonDatasetInfoAllOf';
import JsonMDNAUserObject from './model/JsonMDNAUserObject';
import JsonMDNCertificate from './model/JsonMDNCertificate';
import JsonMDNData from './model/JsonMDNData';
import JsonMDNMailAddress from './model/JsonMDNMailAddress';
import JsonMDNOAuthToken from './model/JsonMDNOAuthToken';
import JsonMDNPasswordReset from './model/JsonMDNPasswordReset';
import JsonMDNSetting from './model/JsonMDNSetting';
import JsonMDNSocialUserObject from './model/JsonMDNSocialUserObject';
import JsonMDNToken from './model/JsonMDNToken';
import JsonMDNUser from './model/JsonMDNUser';
import JsonMDNUserAllOf from './model/JsonMDNUserAllOf';
import JsonMDNUserCredentials from './model/JsonMDNUserCredentials';
import JsonMDNUserProfileImage from './model/JsonMDNUserProfileImage';
import JsonMDNUserSetting from './model/JsonMDNUserSetting';
import JsonMDNUserSettingAllOf from './model/JsonMDNUserSettingAllOf';
import JsonNodeInfo from './model/JsonNodeInfo';
import JsonSignedData from './model/JsonSignedData';
import XmlNs0MDNSetting from './model/XmlNs0MDNSetting';
import XmlNs0MDNSettingAllOf from './model/XmlNs0MDNSettingAllOf';
import XmlNs0MDNUserProfileImage from './model/XmlNs0MDNUserProfileImage';
import XmlNs0MDNUserProfileImageAllOf from './model/XmlNs0MDNUserProfileImageAllOf';
import XmlNs0MDNUserSetting from './model/XmlNs0MDNUserSetting';
import XmlNs0MDNUserSettingAllOf from './model/XmlNs0MDNUserSettingAllOf';
import XmlNs0SignedData from './model/XmlNs0SignedData';
import XmlNs0SignedDataAllOf from './model/XmlNs0SignedDataAllOf';
import AccountServiceApi from './api/AccountServiceApi';
import AuthenticationServiceApi from './api/AuthenticationServiceApi';
import CertificateServiceApi from './api/CertificateServiceApi';
import DataCollectionServiceApi from './api/DataCollectionServiceApi';
import NodeServiceApi from './api/NodeServiceApi';
import OrganizationServiceApi from './api/OrganizationServiceApi';
import RequestServiceApi from './api/RequestServiceApi';
import SocialPlatformServiceApi from './api/SocialPlatformServiceApi';
import SocialServiceApi from './api/SocialServiceApi';
import SystemServiceApi from './api/SystemServiceApi';
import UserServiceApi from './api/UserServiceApi';


/**
* h1API_Quickstart_Guide_h1_______pThis_documentation_contains_a_Quickstart_Guide_a_few_a_hrefdownloads_htmlsample_clients_a__for_download_and_information_about_the_available__a_hrefresources_htmlendpoints_a__and__a_hrefdata_htmlDataTypes_a___p___pThe_a_target_blank_hrefhttp__madana_explorer_staging_eu_central_1_elasticbeanstalk_com_login__MADANA_Explorer_a_can_be_used_to_verify_the_interactions_with_the_API_p_________pInternal_use_only__For_more_information_visit_a_hrefhttps__www_madana_iowww_madana_io_a_p______br_br.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var MadanaSampleclientJavascript = require('index'); // See note below*.
* var xxxSvc = new MadanaSampleclientJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new MadanaSampleclientJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new MadanaSampleclientJavascript.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new MadanaSampleclientJavascript.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.4.12
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The JsonAnalysis model constructor.
     * @property {module:model/JsonAnalysis}
     */
    JsonAnalysis,

    /**
     * The JsonAnalysisAllOf model constructor.
     * @property {module:model/JsonAnalysisAllOf}
     */
    JsonAnalysisAllOf,

    /**
     * The JsonAnalysisRequest model constructor.
     * @property {module:model/JsonAnalysisRequest}
     */
    JsonAnalysisRequest,

    /**
     * The JsonAnalysisRequestAction model constructor.
     * @property {module:model/JsonAnalysisRequestAction}
     */
    JsonAnalysisRequestAction,

    /**
     * The JsonAnalysisResult model constructor.
     * @property {module:model/JsonAnalysisResult}
     */
    JsonAnalysisResult,

    /**
     * The JsonAnalysisResultSubGroup model constructor.
     * @property {module:model/JsonAnalysisResultSubGroup}
     */
    JsonAnalysisResultSubGroup,

    /**
     * The JsonAnalysisResultSubGroupAllOf model constructor.
     * @property {module:model/JsonAnalysisResultSubGroupAllOf}
     */
    JsonAnalysisResultSubGroupAllOf,

    /**
     * The JsonAnalysisVisualization model constructor.
     * @property {module:model/JsonAnalysisVisualization}
     */
    JsonAnalysisVisualization,

    /**
     * The JsonDatasetInfo model constructor.
     * @property {module:model/JsonDatasetInfo}
     */
    JsonDatasetInfo,

    /**
     * The JsonDatasetInfoAllOf model constructor.
     * @property {module:model/JsonDatasetInfoAllOf}
     */
    JsonDatasetInfoAllOf,

    /**
     * The JsonMDNAUserObject model constructor.
     * @property {module:model/JsonMDNAUserObject}
     */
    JsonMDNAUserObject,

    /**
     * The JsonMDNCertificate model constructor.
     * @property {module:model/JsonMDNCertificate}
     */
    JsonMDNCertificate,

    /**
     * The JsonMDNData model constructor.
     * @property {module:model/JsonMDNData}
     */
    JsonMDNData,

    /**
     * The JsonMDNMailAddress model constructor.
     * @property {module:model/JsonMDNMailAddress}
     */
    JsonMDNMailAddress,

    /**
     * The JsonMDNOAuthToken model constructor.
     * @property {module:model/JsonMDNOAuthToken}
     */
    JsonMDNOAuthToken,

    /**
     * The JsonMDNPasswordReset model constructor.
     * @property {module:model/JsonMDNPasswordReset}
     */
    JsonMDNPasswordReset,

    /**
     * The JsonMDNSetting model constructor.
     * @property {module:model/JsonMDNSetting}
     */
    JsonMDNSetting,

    /**
     * The JsonMDNSocialUserObject model constructor.
     * @property {module:model/JsonMDNSocialUserObject}
     */
    JsonMDNSocialUserObject,

    /**
     * The JsonMDNToken model constructor.
     * @property {module:model/JsonMDNToken}
     */
    JsonMDNToken,

    /**
     * The JsonMDNUser model constructor.
     * @property {module:model/JsonMDNUser}
     */
    JsonMDNUser,

    /**
     * The JsonMDNUserAllOf model constructor.
     * @property {module:model/JsonMDNUserAllOf}
     */
    JsonMDNUserAllOf,

    /**
     * The JsonMDNUserCredentials model constructor.
     * @property {module:model/JsonMDNUserCredentials}
     */
    JsonMDNUserCredentials,

    /**
     * The JsonMDNUserProfileImage model constructor.
     * @property {module:model/JsonMDNUserProfileImage}
     */
    JsonMDNUserProfileImage,

    /**
     * The JsonMDNUserSetting model constructor.
     * @property {module:model/JsonMDNUserSetting}
     */
    JsonMDNUserSetting,

    /**
     * The JsonMDNUserSettingAllOf model constructor.
     * @property {module:model/JsonMDNUserSettingAllOf}
     */
    JsonMDNUserSettingAllOf,

    /**
     * The JsonNodeInfo model constructor.
     * @property {module:model/JsonNodeInfo}
     */
    JsonNodeInfo,

    /**
     * The JsonSignedData model constructor.
     * @property {module:model/JsonSignedData}
     */
    JsonSignedData,

    /**
     * The XmlNs0MDNSetting model constructor.
     * @property {module:model/XmlNs0MDNSetting}
     */
    XmlNs0MDNSetting,

    /**
     * The XmlNs0MDNSettingAllOf model constructor.
     * @property {module:model/XmlNs0MDNSettingAllOf}
     */
    XmlNs0MDNSettingAllOf,

    /**
     * The XmlNs0MDNUserProfileImage model constructor.
     * @property {module:model/XmlNs0MDNUserProfileImage}
     */
    XmlNs0MDNUserProfileImage,

    /**
     * The XmlNs0MDNUserProfileImageAllOf model constructor.
     * @property {module:model/XmlNs0MDNUserProfileImageAllOf}
     */
    XmlNs0MDNUserProfileImageAllOf,

    /**
     * The XmlNs0MDNUserSetting model constructor.
     * @property {module:model/XmlNs0MDNUserSetting}
     */
    XmlNs0MDNUserSetting,

    /**
     * The XmlNs0MDNUserSettingAllOf model constructor.
     * @property {module:model/XmlNs0MDNUserSettingAllOf}
     */
    XmlNs0MDNUserSettingAllOf,

    /**
     * The XmlNs0SignedData model constructor.
     * @property {module:model/XmlNs0SignedData}
     */
    XmlNs0SignedData,

    /**
     * The XmlNs0SignedDataAllOf model constructor.
     * @property {module:model/XmlNs0SignedDataAllOf}
     */
    XmlNs0SignedDataAllOf,

    /**
    * The AccountServiceApi service constructor.
    * @property {module:api/AccountServiceApi}
    */
    AccountServiceApi,

    /**
    * The AuthenticationServiceApi service constructor.
    * @property {module:api/AuthenticationServiceApi}
    */
    AuthenticationServiceApi,

    /**
    * The CertificateServiceApi service constructor.
    * @property {module:api/CertificateServiceApi}
    */
    CertificateServiceApi,

    /**
    * The DataCollectionServiceApi service constructor.
    * @property {module:api/DataCollectionServiceApi}
    */
    DataCollectionServiceApi,

    /**
    * The NodeServiceApi service constructor.
    * @property {module:api/NodeServiceApi}
    */
    NodeServiceApi,

    /**
    * The OrganizationServiceApi service constructor.
    * @property {module:api/OrganizationServiceApi}
    */
    OrganizationServiceApi,

    /**
    * The RequestServiceApi service constructor.
    * @property {module:api/RequestServiceApi}
    */
    RequestServiceApi,

    /**
    * The SocialPlatformServiceApi service constructor.
    * @property {module:api/SocialPlatformServiceApi}
    */
    SocialPlatformServiceApi,

    /**
    * The SocialServiceApi service constructor.
    * @property {module:api/SocialServiceApi}
    */
    SocialServiceApi,

    /**
    * The SystemServiceApi service constructor.
    * @property {module:api/SystemServiceApi}
    */
    SystemServiceApi,

    /**
    * The UserServiceApi service constructor.
    * @property {module:api/UserServiceApi}
    */
    UserServiceApi
};
